services:
  map-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollebo/maps-http-server
    volumes:
      - ./code:/code
    ports:
      - 8888:8080
    environment:
      - S3_ENDPOINT=minio.server.robots.beer
      - AWS_S3_FILE_BUCKET=public-ollebo-com
      - AWS_ACCESS_KEY_ID=4Y6Ksc64SxfCciXgLqt0
      - AWS_SECRET_ACCESS_KEY=BvRdpVwh99xQUR6FGMzFklAySzkBOZBfr5JrJ60o
      - REDIS_HOST=redis
      - REDIS_PORT=6379

