services:
  map-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollebo/maps-http-server:0.4
    volumes:
      - ./code:/code
    ports:
      - 8888:8080
    environment:
      - S3_ENDPOINT=minio.server.robots.beer
      - AWS_S3_FILE_BUCKET=lifeandshell
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - REDIS_HOST=redis
      - REDIS_PORT=6379

