kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
   name: "public-maps-ollebo-com"
   namespace: ollebo
   annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "http"
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - maps.ollebo.com
    secretName: maps-ollebo-tls
  rules:
    - host: maps.ollebo.com
      http:
        paths:
        - backend:
            service:
              name: {{ .Values.name }}
              port:
                number: 8080
          path: /
          pathType: Prefix
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
   name: "private-maps-ollebo-com"
   namespace: ollebo
   annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "http"
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - maps-private.ollebo.com
    secretName: maps-private-ollebo-tls
  rules:
    - host: maps-private.ollebo.com
      http:
        paths:
        - backend:
            service:
              name: {{ .Values.name }}
              port:
                number: 8080
          path: /
          pathType: Prefix